# Configuration file for "c_and_q"
# How to use see:
# https://ballerina.io/learn/provide-values-to-configurable-variables/#provide-via-toml-syntax


# "mlDsaKeystore" is an optional value
# mlDsaKeystore = ""	# Type of STRING

# "rsaKeystore" is an optional value
# rsaKeystore = ""	# Type of STRING

# "alias" is an optional value
# alias = ""	# Type of STRING

keystorePassword = "password"	# Type of STRING

